jobs:
  build_and_push:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Run script/ci
          command: ./script/ci

workflows:
  version: 2
  build_and_push:
    jobs:
      - build_and_push
