#!/bin/bash -e

apt-get update -qq

apt-get upgrade -y

echo "------------------------"
echo "Installing dependencies"
echo "------------------------"
DEBIAN_FRONTEND=noninteractive apt-get install -y \
  build-essential \
  ca-certificates \
  curl \
  git \
  libcurl4-openssl-dev \
  libgmp-dev \
  libpcre3 \
  libpcre3-dev \
  libpq-dev \
  libsqlite3-dev \
  libssl-dev \
  openssl \
  python \
  software-properties-common \
  tzdata

echo "------------------------"
echo "Installing node"
echo "------------------------"
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
nvm install ${NODE_VERSION}
npm install -g yarn

echo "------------------------"
echo "Installing ruby"
echo "------------------------"
curl -fL https://github.com/postmodern/ruby-install/archive/v0.7.0.tar.gz | tar zxvf -
cd ruby-install-0.7.0 && make install
ruby-install --system ruby ${RUBY_VERSION} -- --disable-install-rdoc --disable-install-ri
gem update --system

echo "------------------------"
echo "Installing passenger and nginx"
echo "------------------------"
gem install passenger -v ${PASSENGER_VERSION}

curl -fL http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz | tar zxvf -
cd nginx-${NGINX_VERSION}
./configure \
  --prefix=/usr/local/bin \
  --sbin-path=nginx \
  --conf-path=/etc/nginx/nginx.conf \
  --with-http_ssl_module \
  --with-http_gzip_static_module \
  --add-module=${GEM_HOME}/gems/passenger-${PASSENGER_VERSION}/src/nginx_module/
make
make install
mkdir -p /etc/nginx/sites-enabled
cd ..

echo "------------------------"
echo "Creating passenger user"
echo "------------------------"
addgroup --gid 9999 app
adduser --home "/home/app/" --uid 9999 --gid 9999 --disabled-password --gecos "Application User" app
usermod -L app

echo "------------------------"
echo "Cleaning up"
echo "------------------------"
apt-get -q clean
rm -rf /var/lib/apt/list/*
rm -rf /usr/local/src/*
rm -rf ruby-install-*
rm -rf nginx-${NGINX_VERSION}*
rm -rf node-${NODE_VERSION}
